"""add owner name to repositories

Revision ID: 8b8512e42ee5
Revises: 3fb83be14b3b
Create Date: 2026-06-02 21:00:03.419762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b8512e42ee5'
down_revision: Union[str, Sequence[str], None] = '3fb83be14b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('owner_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'owner_name')
    # ### end Alembic commands ###
