"""add user embeddins and skill rofile

Revision ID: d7f84bb0055e
Revises: e0a72dccb4bc
Create Date: 2026-06-03 12:38:44.434938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7f84bb0055e'
down_revision: Union[str, Sequence[str], None] = 'e0a72dccb4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skill_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('users', 'skill_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('skill_vector', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('users', 'skill_profile')
    # ### end Alembic commands ###
